### ISSUE TITLE
Why the number of clusters is different in JaccardRainCloudPlot vs Umap plot with the selected combination of parameters

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/scclusteval#13]
Hi @crazyhottommy 
I did run the scclusteval and ended up finding the best combination of parameters. But when I try to reproduce the clustering by running Umap it doesn't out put the same number of clusters. I mean in JaccardRainCloudPlot I have 26 clusters but in my umap plot they are 27 and I'm not sure whether the clusters correspond to the right one between these two. Could you please let me know which step I should follow after getting the .rds data from full_sample_preprocess folder? after getting the .rds I did run RunUMAP as it doesn't have umap. 
Thanks,
Paria

**Comment by crazyhottommy** [comment]
Hi, if you decided the best PC, k and resolution by scclusteval,
you should go to `full_sample_preprocess/full_sample_k_{k}_resolution_{resolution}_PC_{pc}.rds` and get the corresponding Seurat object and it should have the same number of clusters

**Comment by Jay-Leung** [comment]
Hi Ming Tang,

I had run scclusteval and went ahead to do the clustering with the identified parameters in Seurat directly, but it gave me 9 clusters instead of the 10 by scclusteval at those parameters. I looked through the script and I think the issue is that scclusteval runs with the default Louvain algorithm, while in Seurat I run Leiden. So if this is the case, I should modify the preprocess script to Leiden algorithm, is that right? In Seurat this requires the leidenalg python package to be installed, so I am not sure how it would work in scclusteval. 

Thanks!

**Comment by crazyhottommy** [comment]
correct. you will need to add the parameter `algorithm = 4`  at https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/scripts/preprocess.R#L79 and https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/scripts/subsample.R#L95

**Comment by Jay-Leung** [comment]
Alright, got it, will rerun it. Thanks so much!
